name: Build Vite App

on:
  workflow_dispatch:
  push:
      branches: [main]
  pull_request:
      branches: [main]

jobs:
  build-vite-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build with Vite
        run: npm run build
